Lab_5/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path, include

from app import views

app_name = 'app'

urlpatterns = [
    path('', views.Home, name='home'),
    path('create/', views.ProductCreate.as_view(), name='create'),
    path('update/<int:id>/', views.ProductUpdate.as_view(), name='update'),
    path('delete/<int:id>/', views.ProductDelete.as_view(), name='delete'),
    path('<int:id>/', views.Detail, name='detail'),
]

app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Brand(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=30)
    price = models.IntegerField(default=0)
    description = models.TextField(blank=True)
    picture = models.ImageField(upload_to='product_pictures', default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('app:detail',
                       args=[self.id])

app/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Brand, Product
from django.views.generic.edit import CreateView, UpdateView, DeleteView


def navigation(request):
    brand_list = Brand.objects.all()
    context = {
        'brand_list': brand_list,
    }
    return context

def Home(request):
    product_list = Product.objects.all().order_by('-created_at')

    context = {
        'product_list': product_list,
    }

    return render(request, 'app/home.html', context)


def Detail(request, id):
    product_item = Product.objects.get(id=id)
    product_list = Product.objects.all()

    context = {
        'product_item': product_item,
        'product_list': product_list,
    }

    return render(request, 'app/detail.html', context)


class ProductCreate(CreateView):
    model = Product
    fields = ['name', 'price', 'description', 'picture', 'brand']

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

class ProductUpdate(UpdateView):
    model = Product
    fields = ['name', 'price', 'description', 'picture', 'brand']

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Product, id=id_)

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

class ProductDelete(DeleteView):

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Product, id=id_)

    def get_success_url(self):
        return reverse('app:home')

templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body>
{% block title %}{% endblock %}
<div style="padding: 10px 300px 10px 300px;">
    {% block navbar %}
        {% include "navigation.html" %}
    {% endblock %}
    {% block content %}{% endblock %}
    {% block footer %}{% endblock %}
</div>
</body>
</html>

templates/app/detail.html
{% extends 'app/base.html' %}
{% load humanize %}
{% block title %}<title>Chi tiết</title>{% endblock %}
{% block content %}
    <div style="margin-top: 50px; display: flex; justify-content: space-between;">
        <div style="flex: 1; margin-right: 20px;">
            <div style="display: flex; flex: 1; justify-content: space-between;">
                <p>
                    Đăng tải lúc: {{ product_item.created_at }}
                </p>
                <p>
                    Cập nhật: {{ product_item.updated_at }}
                </p>
            </div>
            <div style="flex: 1; min-height: 500px;background-color: #f2eedf; padding: 20px 50px 20px 50px;">
                <h4 style="color: #b53c4c;">
                    {{ product_item.name }}
                </h4>
                <p>
                    {{ product_item.description }}
                </p>
            </div>
        </div>
        <div style="align-items: center; margin-top: 40px;">
            <div style="width: 400px; height: 400px;">
                    <img style="width: 100%; height: 100%; object-fit: contain;"
                         src="{{ product_item.picture.url }}" alt="">
            </div>
            <h4 style="text-align: center; margin-top: 10px; color: #b53c4c;">
                Giá: {{ product_item.price|intcomma }} VND
            </h4>

        </div>
    </div>

    <div style="flex: 1; height: 2px;background-color: darkgray; margin-top: 20px;"></div>


    <p style="margin-top: 10px;">
        Số sản phẩm hiện có: {{ product_list.count }}
    </p>
    </div>{% endblock %}

templates/app/home.html
{% extends 'app/base.html' %}
{% load humanize %}
{% block title %}<title>Trang chủ</title>{% endblock %}
{% block content %}
    <div style="margin-top: 50px; display: flex; justify-content: center;">
        <input style="width: 350px; height: 30px; padding-left: 10px;" placeholder="Nhập sản phẩm muốn tìm..."
               type="text" name="" id="">
        <button
                style="background-color: #4166b2; color: azure; border: none; padding: 0px 15px 0px 15px; margin-left: 5px;">
            Tìm kiếm
        </button>
    </div>
    {% for product_item in product_list %}
        <div style="display: flex; align-items: center;">
            <div style="padding: 0px 30px 0px 100px; margin-top: 30px;">
                <div
                        style="display: flex; flex-direction: row; flex: 1; background-color:#94bce0; padding: 20px 50px 20px 50px; ">
                    <img style="width: 150px; height: 150px; object-fit: contain;"
                         src="{{ product_item.picture.url }}"
                         alt="">
                    <div style="display: flex; flex-direction: column;">
                        <div style=" margin-left: 20px;display: flex; flex: 1; justify-content:space-between">
                            <h3>
                                <a style="color: black;" href="{{ product_item.get_absolute_url }}">
                                    {{ product_item.name }}
                                </a>
                            </h3>
                            <h4 style="color: #b53c4c;">Giá: {{ product_item.price|intcomma }}VND</h4>
                        </div>
                        <div style=" margin-left: 20px;">
                            <p>
                                {{ product_item.description }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <a href="{% url 'app:update' product_item.id %}">
                    <button style="width: 100px;" class="btn btn-primary">

                        Chỉnh sửa
                    </button>
                </a>
                <a href="{% url 'app:delete' product_item.id %}">
                    <button style="width: 100px;margin-top: 15px;" class=" btn btn-danger">
                        Xoá
                    </button>
                </a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/app/product_confirm_delete.html
{% extends 'app/base.html' %}
{% block title %}<title>Trang chủ</title>{% endblock %}
{% block content %}
    <div style="margin-top: 50px; display: flex; justify-content: space-between;">
        <div style="width: 55%;">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>Bạn chắc chắn muốn xóa "{{ object.name }}"?</p>
                <input type="submit" value="Confirm"/>
            </form>
        </div>
    </div>
{% endblock %}

templates/app/product_form.html
{% extends 'app/base.html' %}
{% block title %}<title>Trang chủ</title>{% endblock %}
{% block content %}
    <div style="margin-top: 50px; display: flex; justify-content: space-between;">
        <div style="width: 55%;">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save"/>
            </form>
        </div>
    </div>
{% endblock %}

templates/app/product_update_form.html
{% extends 'app/base.html' %}
{% load navigation_tags %} {% brand_list %}
{% block title %}<title>Trang chủ</title>{% endblock %}
{% block content %}
    <div style="margin-top: 50px; display: flex; justify-content: space-between;">
        <div style="width: 55%;">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Update"/>
            </form>
        </div>
    </div>
{% endblock %}

templates/navigation.html
<nav style="display: flex; justify-content: space-between; align-items: center; ">
    <a style="padding: 10px 35px 10px 35px; background-color: #4166b2; text-decoration: none; color: azure;"
       href="{% url 'app:home' %}">Home</a> |
    <a style="color: #4166b2; text-decoration: none;" href="{% url 'app:create' %}">Tạo sản phẩm</a> |
    {% for brand_item in brand_list %}
        <a style="color: #4166b2; text-decoration: none;" href="#">{{ brand_item.name }}</a> |
    {% endfor %}
</nav>